name: Android CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build APK for testing
        run: ./gradlew test check assembleObaGoogleDebug -x lint --stacktrace

      - name: Upload APK for testing
        uses: actions/upload-artifact@v4
        with:
          name: apk-test-${{ github.run_number }}
          path: |
            **/build/outputs/apk/**/*.apk
          if-no-files-found: error
          retention-days: 7
